export enum EVENT_LIST {
  GET_INSTRUMENT_LIST = "GET_INSTRUMENT_LIST",
  GET_POSITION_INSTRUMENT_LIST = "GET_POSITION_INSTRUMENT_LIST",
  SET_TRADE_MODE_INSTRUMENT_LIST = "SET_TRADE_MODE_INSTRUMENT_LIST",
  SET_LEVERAGE_INSTRUMENT_LIST = "SET_LEVERAGE_INSTRUMENT_LIST",
  GET_CANDLES_INSTRUMENT_LIST = "GET_CANDLES_INSTRUMENT_LIST",
  FILTER_PRICE_STEP_INSTRUMENT_LIST = "FILTER_PRICE_STEP_INSTRUMENT_LIST",
  CALCULATE_SMMA_INSTRUMENT_LIST = "CALCULATE_SMMA_INSTRUMENT_LIST",
  FILTER_LAST_PRICE_IN_SMMA_INSTRUMENT_LIST = "FILTER_LAST_PRICE_IN_SMMA_INSTRUMENT_LIST",
  SUBSCRIBE_WEBSOCKET_INSTRUMENT_LIST = "SUBSCRIBE_WEBSOCKET_INSTRUMENT_LIST",
}
